feat: support node18
KasimAhmic/lib-native pull request #1
Opened 2024-08-21 06:57 UTC by cxgreat2014

feat: support node18
    fix: fix encoding issue
    fix: correct paramsType for MessageBoxW

    RelatedIssue: https://github.com/zhangyuang/node-ffi-rs/issues/68

2024-08-21 07:17 UTC, cxgreat2014 commented on src/util/logger.ts
> +    let styleFunction: any = chalk[style];
A better solution than using any might be available here.

2024-08-23 11:53 UTC, KasimAhmic requested changes
Thanks for the PR, good catch on the type issues! If you could just update the type in the logger, I can merge this!

2024-08-23 11:53 UTC, KasimAhmic commented on src/util/logger.ts
> +}
We can import the various types from Chalk and use those to construct our style type.

```typescript
import chalk, { BackgroundColorName, ColorName, ForegroundColorName, ModifierName } from "chalk";

type ChalkStyle =
  | ModifierName
  | ForegroundColorName
  | BackgroundColorName
  | ColorName;

function styleText(styles: ChalkStyle[], text: string): string {
  let styledText = text;

  styles.forEach((style) => {
    const styleFunction = chalk[style];

    if (styleFunction instanceof Function) {
      styledText = styleFunction(styledText);
    }
  });

  return styledText;
}
```

2024-08-26 23:28 UTC, KasimAhmic approved these changes

2024-08-26 23:29 UTC, merged

2024-08-26 23:29 UTC, KasimAhmic commented
Merged, thank you!